services:
  api:
    build: .
    container_name: hackrx-doc-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data        # keeps Chroma & SQLite persistent on local disk
